In [67]:
import dnc
import torch
import torch.nn as nn

In [100]:
rnn = dnc.DNC(
  input_size=103,#64,
  hidden_size=128,
  rnn_type='lstm',
  num_layers=4,
  nr_cells=100,
  cell_size=32,
  read_heads=4,
  batch_first=True,
  gpu_id=-1,
  debug=True
)


In [102]:
(controller_hidden, memory, read_vectors) = (None, None, None)

output, (controller_hidden, memory, read_vectors), debug_memory = \
  rnn(torch.randn(1, 3, 103), (controller_hidden, memory, read_vectors), reset_experience=True)

In [103]:
output.shape

torch.Size([1, 3, 103])

In [12]:
controller_hidden[0]

(tensor([[[-4.4760e-02,  5.6892e-02,  9.6455e-02,  ...,  1.6225e-01,
           -6.5476e-02,  3.1672e-02],
          [-2.1729e-02, -9.3663e-03,  1.0523e-01,  ...,  2.1579e-01,
           -1.5778e-01, -1.2064e-02],
          [-1.9702e-01,  1.9940e-01,  1.7859e-01,  ..., -4.3118e-02,
            5.7821e-02,  5.2900e-03],
          ...,
          [ 2.8990e-03, -6.5009e-02, -1.7719e-01,  ..., -1.5704e-01,
            7.2187e-02,  2.5699e-02],
          [-4.4261e-02, -1.5266e-01, -8.4843e-02,  ..., -5.9853e-03,
           -5.4827e-02,  4.2761e-03],
          [-3.1246e-02, -1.3804e-01,  2.8914e-02,  ..., -7.3456e-02,
            4.1136e-02, -7.3873e-02]],
 
         [[-2.2833e-02,  4.8604e-02, -5.7187e-02,  ...,  1.4431e-02,
           -2.8897e-02, -1.0005e-02],
          [-3.5406e-03,  3.2472e-02, -4.6823e-02,  ..., -1.7770e-02,
           -2.2689e-02, -1.5206e-02],
          [ 2.2211e-02,  8.2979e-03, -6.9662e-02,  ...,  1.8660e-03,
           -4.3914e-03, -2.0629e-02],
          ...,
    

In [15]:
memory.keys()

dict_keys(['memory', 'link_matrix', 'precedence', 'read_weights', 'write_weights', 'usage_vector'])

In [17]:
memory['usage_vector'].shape

torch.Size([10, 100])

In [21]:
def mθ(message):
    print(message, "*w🤪ink* *wink*")

In [22]:
mθ("hello there")

hello there *w🤪ink* *wink*


In [1]:
import sys

In [7]:
'numpy' in sys.modules

True

In [6]:
import numpy

In [3]:
# for some reason you have to import this twice for it to work...
from rugstk.data.munroecorpus import munroecorpus

In [4]:
munroecorpus

<module 'rugstk.data.munroecorpus.munroecorpus' from '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/munroecorpus.py'>

In [6]:
training_handles = munroecorpus.get_training_handles()

In [9]:
training_handles[0]

{'acid green': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/acidgreen.h_train',
 'adobe': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/adobe.h_train',
 'algae': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/algae.h_train',
 'algae green': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/algaegreen.h_train',
 'almost black': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/almostblack.h_train',
 'amber': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/amber.h_train',
 'amethyst': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/amethyst.h_tra

In [10]:
training_handles[1]

{'acid green': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/acidgreen.s_train',
 'adobe': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/adobe.s_train',
 'algae': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/algae.s_train',
 'algae green': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/algaegreen.s_train',
 'almost black': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/almostblack.s_train',
 'amber': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/amber.s_train',
 'amethyst': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/amethyst.s_tra

In [11]:
training_handles[2]

{'acid green': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/acidgreen.v_train',
 'adobe': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/adobe.v_train',
 'algae': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/algae.v_train',
 'algae green': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/algaegreen.v_train',
 'almost black': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/almostblack.v_train',
 'amber': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/amber.v_train',
 'amethyst': '/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/amethyst.v_tra

In [17]:
hs = {color:munroecorpus.open_datafile(training_handles[0][color]) for color in training_handles[0].keys()}

In [20]:
ss = {color:munroecorpus.open_datafile(training_handles[1][color]) for color in training_handles[1].keys()}

In [21]:
vs = {color:munroecorpus.open_datafile(training_handles[2][color]) for color in training_handles[2].keys()}

In [31]:
hsvs = {}
for color in hs.keys():
    hsvs[color] = list(zip(hs[color], ss[color], vs[color]))


In [42]:
hsvs['bright green']

[(96.47058823524, 94.4444444444, 84.70588235289999),
 (107.38853503200001, 82.6315789474, 74.50980392160001),
 (119.45945945951999, 90.243902439, 96.4705882353),
 (111.56756756760001, 78.3898305085, 92.5490196078),
 (101.53846153836, 87.4439461883, 87.4509803922),
 (117.30941704044, 87.7952755906, 99.6078431373),
 (146.51162790696, 97.72727272729999, 86.2745098039),
 (111.47727272724, 74.2616033755, 92.9411764706),
 (119.69072164944001, 78.5425101215, 96.862745098),
 (95.02890173424001, 80.8411214953, 83.9215686275),
 (127.74193548372, 94.347826087, 90.1960784314),
 (100.00000000008001, 89.3617021277, 92.1568627451),
 (115.5445544556, 95.28301886790001, 83.137254902),
 (118.484848485, 86.0869565217, 90.1960784314),
 (74.67391304352, 92.0, 78.431372549),
 (114.63157894752, 88.785046729, 83.9215686275),
 (129.14798206284, 94.4915254237, 92.5490196078),
 (142.30088495568, 89.3280632411, 99.2156862745),
 (120.81447963791999, 92.46861924689999, 93.7254901961),
 (124.32989690712002, 81.85654

In [33]:
train_data = []
for color in hsvs.keys():
    for hsv in hsvs[color]:
        train_data.append([color, hsv])

In [40]:
from collections import defaultdict

In [ ]:
vocab = defaultdict(0)

In [43]:
word2idx = {'<sos>':0, '<eos>':1, '<unk>':2}
idx2word = {0:'<sos>', 1:'<eos>', 2:'<unk>'}
i=3
for color in hsvs.keys():
    words = color.split(" ") # pretty nicely formatted
    for word in words:
        if not word in word2idx:
            word2idx[word] = i
            idx2word[i] = word
            i += 1

# add padding token
word2idx['<pad>'] = i
idx2word[i] = '<pad>'
i+= 1
    

In [212]:
word2idx['<pad>'] = i
idx2word[i] = '<pad>'
i+= 1

In [213]:
word2idx['<pad>']

367

In [214]:
idx2word[367]

'<pad>'

In [210]:
len(word2idx)

367

In [221]:
max_len = max(len(train_data[i][0].split()) for i in range(len(train_data)))

In [41]:
train_data[4]

['fawn', (23.703703703711998, 41.5384615385, 76.4705882353)]

In [227]:
a = [1]
a.extend([2]*0)

In [228]:
a

[1]

In [25]:
import numpy as np

In [49]:
np.array([[1],(1, 2, 3)])

array([list([1]), (1, 2, 3)], dtype=object)

In [232]:
# max_len = max(len(train_data[i][0].split()) for i in range(len(train_data)))
train_data_np = []
train_data_seq_lens = []
for color in train_data:
    color_name, hsv = color
    color_name_np = [word2idx[word_part] for word_part in ["<sos>"] + color_name.split(" ") + ["<eos>"]]
    train_data_seq_lens.append(len(color_name_np))
    color_name_np.extend([word2idx['<pad>']] * (max_len - len(color_name_np) + 2)) # + 2 for sos and eos
    hsv_np = np.array(hsv)
    train_data_np.append([color_name_np, hsv_np])

In [233]:
train_data_np[400]

[[0, 7, 8, 1, 367], array([243.48387097,  61.50793651,  98.82352941])]

In [234]:
train_data_seq_lens[400]

4

In [55]:
idx2word[8]

'periwinkle'

In [27]:
train_data[0]

['fawn',
 [50.13698630148,
  38.31325301196,
  32.805755395668,
  44.77611940308,
  23.703703703711998,
  44.499999999959996,
  38.94039735084,
  36.92307692304,
  337.5,
  49.444444444320006,
  57.4468085106,
  45.483870967920005,
  42.00000000012,
  8.57142857142,
  32.658227848116,
  41.81818181832,
  36.296296296120005,
  33.986013986016,
  63.9344262294,
  20.800000000008,
  37.62711864396,
  52.57731958776,
  52.17391304352,
  21.355932203388,
  43.99999999992,
  22.222222222212,
  42.85714285728,
  42.93577981656,
  58.9830508476,
  38.63013698628,
  38.21656050972,
  43.99999999992,
  29.032258064508,
  48.717948718079995,
  24.374999999988,
  56.51162790696,
  32.359550561784,
  52.59259259243999,
  60.000000000120004,
  37.75280898888,
  52.31999999988,
  58.588235294040004,
  24.406779661020003,
  69.99999999984,
  36.26373626388,
  47.44186046496,
  39.1836734694,
  22.799999999988003,
  44.4705882354,
  46.415094339599996,
  34.166666666664,
  23.076923076935998,
  18.6206

In [15]:
len(df)*len(training_handles[0])

246213

In [12]:
for i in training_handles[0].keys():
    print(i)

fawn
light grey blue
dark periwinkle
light lilac
clay brown
peacock blue
carnation pink
pale violet
yellow
cobalt
camouflage green
lemon lime
minty green
deep violet
ugly pink
skin
dull red
apple green
sea blue
darkish purple
gold
dark slate blue
prussian blue
deep purple
yellow ochre
dark maroon
vomit green
crimson
marine blue
brown
green-yellow
sage green
red-orange
royal purple
easter green
purpley blue
mid blue
hiccup
seafoam blue
dark plum
asparagus
light burgundy
dark mint green
greenish teal
greyish green
sand
brownish
brownish purple
teal
greenish
green-brown
dusty green
brown-orange
sunflower yellow
pinky purple
bright fuchsia
blood red
neon pink
navy green
baby blue
rouge
lavender
pink-red
forest green
orangey red
earth
purple-brown
lightish green
sick green
light orange
blue
pale lilac
rich purple
metallic blue
ugly
coral
dark gold
burgundy
bright purple
greenish grey
tan brown
deep teal
pastel pink
light kelly green
orangey brown
acid green
bright aqua
barbie pink
baby pink

In [10]:
training_handles[0]['fawn']

'/Users/benjaminnewman/Documents/Stanford/CS224U/projects/color-dnc-commonground/rugstk/data/munroecorpus/train/fawn.h_train'

In [68]:
len(word2idx)

367

In [322]:
class DNCEncoder(nn.Module):
    def __init__(self, vocab_size, embed_dim, color_dim):
        super(DNCEncoder, self).__init__()
        self.embed = nn.Embedding(vocab_size, embed_dim)
        self.rnn = dnc.DNC(
          input_size=embed_dim + color_dim,
          hidden_size=128,
          rnn_type='lstm',
          num_layers=4,
          nr_cells=100,
          cell_size=32,
          read_heads=4,
          batch_first=True,
          gpu_id=-1,
          debug=True
        )
        self.decoder = nn.Linear(embed_dim + color_dim, vocab_size) # don't predict over padding tag
        self.logsoftmax = nn.LogSoftmax(dim=1)
        
        self.vocab_size = vocab_size
        
    def forward(self, caption, color):
        embeds = self.embed(caption)
        #embeds = nn.utils.pack_padded_sequence(embeds, caption_lens, batch_first=True)
        #print(embeds.type())
        #print(color.type())
        color_reps = color.repeat(1, caption.shape[1], 1) # repeat color for number of tokens in captions
        #print(color_reps)
        # concatenate colors to caption
        inputs = torch.cat((embeds, color_reps), dim=2) # cat along the innermost dimension
        #print(inputs.size())
        # dnc magic
        (controller_hidden, memory, read_vectors) = (None, None, None)
        output, (controller_hidden, memory, read_vectors), debug_memory = \
          rnn(inputs, (controller_hidden, memory, read_vectors), reset_experience=True)


        result = self.decoder(output)
        return self.logsoftmax(result)

In [317]:
dncencoder_test = DNCEncoder(len(word2idx), 100, 3)

In [79]:
train_data_np[0]

[array([0, 3, 1]), array([50.1369863 , 34.27230047, 83.52941176])]

In [125]:
test_in_caption = torch.tensor([train_data_np[0][0], train_data_np[1][0]])

In [126]:
test_in_caption

tensor([[0, 3, 1],
        [0, 3, 1]])

In [127]:
test_in_color = torch.tensor([[train_data_np[0][1]], [train_data_np[1][1]]])

In [128]:
test_in_color = test_in_color.type(torch.FloatTensor)

In [129]:
test_in_color

tensor([[[50.1370, 34.2723, 83.5294]],

        [[38.3133, 35.4701, 91.7647]]])

In [138]:
test_output = dncencoder_test.forward(test_in_caption, test_in_color)

torch.FloatTensor
torch.FloatTensor
torch.Size([2, 3, 103])


In [111]:
test_output.shape

torch.Size([1, 3, 367])

In [131]:
len(train_data_np)

1523108

In [ ]:
# ok, let's incorporate the training code (we don't need featurizers or anything, just the modeling code)

In [133]:
# import sys
# sys.path.append("../color-evaluation/")

In [134]:
import models

In [370]:
# shamelessly copied from beam search code
from queue import PriorityQueue

class BeamNode():
    def __init__(self, log_prob, tokens, ended):
        self.log_prob = log_prob
        self.tokens = tokens
        self.ended = ended

    def score(self):
        return -self.log_prob

    def __eq__(self, other):
        return self.score() == other.score()

    def __lt__(self, other):
        return self.score() < other.score()
    

class DNCSpeaker(PytorchModel):
    
    def predict(self, X, sample=1, beam_width=5):
        all_tokens = []
        self.model.eval()
        max_gen_len = 20
    
        self.model.eval()
        with torch.no_grad():
            for i, feature in enumerate(X):
                caption, colors = feature
                if self.batch_size == 1:
                    caption = torch.tensor([caption], dtype=torch.long)
                    colors = torch.tensor([colors], dtype=torch.float)
                else:
                    caption = torch.tensor([caption], dtype=torch.long)
                    colors = torch.tensor([colors], dtype=torch.float)

    
                beam_nodes = PriorityQueue()
                ended_list = []
    
                tokens = caption[:, 0].view(-1, 1) # begin at start token
                start = BeamNode(0, tokens, False)
                beam_nodes.put(start)
    
                for i in range(max_gen_len + 1):
                    node = beam_nodes.get()
                    if node.ended:
                        ended_list.append(np.array(node.tokens[0].numpy()))
                        if len(ended_list) == sample:
                            break
                    else:
                        tokens = node.tokens
                        vocab_preds = self.model(colors, tokens)[:,-1:,:] # just distribution over last token
                        log_probs, prediction_indices = vocab_preds.topk(beam_width, dim=2)  # taking the topk predictions
                        for j in range(beam_width):
                            prediction_index = prediction_indices[:,-1,j:j+1] # a single prediction
                            log_prob = log_probs[0][0][j].item()
                            updated_tokens = tokens.clone()
                            updated_tokens = torch.cat((updated_tokens, prediction_index), dim=1)
                            updated_log_prob = node.log_prob + log_prob
                            ended = ((i == max_gen_len - 1) or (prediction_index.item() == caption[:, -1].view(-1, 1)))
                            new_node = BeamNode(updated_log_prob, updated_tokens, ended)
                            beam_nodes.put(new_node)
                if sample == 1: # for backwards compatability
                    all_tokens.append(np.array(ended_list))
                else:
                    all_tokens.append(ended_list)
        return all_tokens
    
    def train_iter(self, caption_tensor, color_tensor, target_tensor, criterion):
        model_output = self.model(caption_tensor, color_tensor)
        
        #model_output = model_output[:, :-1, :].squeeze(0)
        model_output = model_output.view(-1, self.model.vocab_size)
        target_tensor = target_tensor.view(-1)
        #print("output shape:", model_output.size())
        #print("target shape:", target_tensor.size())
        loss = criterion(model_output, target_tensor)
        return loss

In [372]:
dnc_speaker = DNCSpeaker(DNCEncoder, num_epochs=5, batch_size=128)
dnc_speaker.init_model(vocab_size = len(word2idx), embed_dim=100, color_dim=3)

In [238]:
train_data_np[:3]

[[[0, 3, 1, 367, 367], array([50.1369863 , 34.27230047, 83.52941176])],
 [[0, 3, 1, 367, 367], array([38.31325301, 35.47008547, 91.76470588])],
 [[0, 3, 1, 367, 367], array([32.8057554 , 78.53107345, 69.41176471])]]

In [239]:
data_pairs = train_data_np

In [147]:
data_pairs[0][1].reshape(1, -1)

array([[50.1369863 , 34.27230047, 83.52941176]])

In [240]:
train_features_np = []
train_targets_np = []
for pair in data_pairs:
    caption, color = pair
    caption_train = caption[:-1]
    caption_test = caption[1:]
    color_train = color.reshape(1, -1)
    train_features_np.append([caption_train, color_train])
    train_targets_np.append([caption_test])

In [ ]:
# kinda sketch but we are just going to try and predict the padding tokens

In [194]:
np.arange(2)

array([0, 1])

In [195]:
train_rand = np.random.permutation(len(train_targets_np))

In [244]:
train_features_np = np.array(train_features_np)#[train_rand]
train_targets_np = np.array(train_targets_np)

In [245]:
train_features_np_rand = train_features_np[train_rand]
train_targets_np_rand = train_targets_np[train_rand]

In [246]:
train_features_np_rand[:10]

array([[list([0, 11, 1, 367]),
        array([[350.4       ,  56.81818182,  51.76470588]])],
       [list([0, 7, 6, 1]),
        array([[244.66019417,  76.86567164,  52.54901961]])],
       [list([0, 132, 20, 1]),
        array([[73.33333333, 52.55474453, 53.7254902 ]])],
       [list([0, 6, 1, 367]),
        array([[215.18518519,  93.10344828,  68.23529412]])],
       [list([0, 168, 1, 367]),
        array([[48.48214286, 88.88888889, 98.82352941]])],
       [list([0, 126, 1, 367]),
        array([[71.56626506, 98.80952381, 65.88235294]])],
       [list([0, 28, 1, 367]),
        array([[357.58928571,  97.81659389,  89.80392157]])],
       [list([0, 11, 1, 367]),
        array([[28.91566265, 87.36842105, 37.25490196]])],
       [list([0, 32, 1, 367]),
        array([[290.52631579,  41.00719424,  54.50980392]])],
       [list([0, 9, 1, 367]),
        array([[264.42477876,  47.28033473,  93.7254902 ]])]],
      dtype=object)

In [248]:
train_targets_np[0]

array([[  3,   1, 367, 367]])

In [249]:
dnc_speaker.fit(train_features_np_rand.tolist(), train_targets_np_rand.tolist())

---EPOCH 0---
0m 0s (0:0 0.00%) 0.0014


KeyboardInterrupt: 

In [207]:
# dnc_speaker.save_model("dnc_speaker_2pcnt.params")

In [260]:
batches = []

for i in range(0, 10, 2):
    batches.append(train_features_np_rand[i: i+2])

In [273]:
batch_np = np.empty([len(train_features_np), len(train_features_np[0][0])], dtype=np.long)
for i in range(len(train_features_np)):
    batch_np[i] = train_features_np_rand[i][0]

In [275]:
captions_np = batch_np

In [277]:
captions_np

array([[  0,  11,   1, 367],
       [  0,   7,   6,   1],
       [  0, 132,  20,   1],
       ...,
       [  0,  79,   1, 367],
       [  0, 236,   1, 367],
       [  0, 167,   1, 367]])

In [280]:
colors_np = np.empty([len(train_features_np), len(train_features_np[0][1][0])])
for i in range(len(train_features_np)):
    colors_np[i] = train_features_np_rand[i][1]

In [340]:
train_targets_np_rand[:2]

array([[[ 11,   1, 367, 367]],

       [[  7,   6,   1, 367]]])

In [281]:
colors_np

array([[350.4       ,  56.81818182,  51.76470588],
       [244.66019417,  76.86567164,  52.54901961],
       [ 73.33333333,  52.55474453,  53.7254902 ],
       ...,
       [ 30.81081081,  83.71040724,  86.66666667],
       [ 43.81395349,  88.1147541 ,  95.68627451],
       [214.09090909,  81.48148148,  21.17647059]])

In [285]:
colors_np = colors_np.reshape(-1, 1, 3)

In [290]:
colors_np[:2]

array([[[350.4       ,  56.81818182,  51.76470588]],

       [[244.66019417,  76.86567164,  52.54901961]]])

In [272]:
train_features_np_rand[1][0]

[0, 7, 6, 1]

In [271]:
batch_np

array([[  0,  11,   1, 367],
       [  0,   7,   6,   1]])

In [258]:
train_features_np_rand[:1]

array([[list([0, 11, 1, 367]),
        array([[350.4       ,  56.81818182,  51.76470588]])]],
      dtype=object)

In [321]:
colors_np[:2]

array([[[350.4       ,  56.81818182,  51.76470588]],

       [[244.66019417,  76.86567164,  52.54901961]]])

In [318]:
test_batch_caps = torch.tensor(captions_np[:2])

In [319]:
test_batch_colors = torch.tensor(colors_np[:2], dtype=torch.float)

In [320]:
# let's try to batch this stuff

dncencoder_test(test_batch_caps, test_batch_colors)



tensor([[[350.4000,  56.8182,  51.7647],
         [350.4000,  56.8182,  51.7647],
         [350.4000,  56.8182,  51.7647],
         [350.4000,  56.8182,  51.7647]],

        [[244.6602,  76.8657,  52.5490],
         [244.6602,  76.8657,  52.5490],
         [244.6602,  76.8657,  52.5490],
         [244.6602,  76.8657,  52.5490]]])


tensor([[[-1.3913, -1.3896, -1.3843,  ..., -1.3930, -1.3874, -1.3957],
         [-1.3882, -1.3862, -1.3864,  ..., -1.3865, -1.3867, -1.3870],
         [-1.3844, -1.3848, -1.3871,  ..., -1.3836, -1.3859, -1.3825],
         [-1.3812, -1.3845, -1.3873,  ..., -1.3822, -1.3852, -1.3801]],

        [[-1.3843, -1.3917, -1.3904,  ..., -1.3906, -1.3866, -1.3787],
         [-1.3869, -1.3865, -1.3878,  ..., -1.3867, -1.3867, -1.3853],
         [-1.3872, -1.3840, -1.3848,  ..., -1.3846, -1.3862, -1.3894],
         [-1.3868, -1.3830, -1.3822,  ..., -1.3833, -1.3857, -1.3918]]],
       grad_fn=<LogSoftmaxBackward>)

In [335]:
batch_size = 128
captions_np_batched = np.split(captions_np, len(captions_np)/batch_size)
colors_np_batched = np.split(colors_np, len(colors_np)/batch_size)

In [348]:
train_targets_np_batched = np.split(train_targets_np_rand.reshape(-1, train_targets_np_rand.shape[-1]), len(train_targets_np_rand)/batch_size)

In [346]:
train_targets_np_rand.shape[-1]

4

In [351]:
len(train_targets_np_batched)

11899

In [337]:
train_features = list(zip(captions_np_batched, colors_np_batched))

In [375]:
dnc_speaker.load_model("checkpoint_0.params")

In [376]:
dnc_speaker.fit(train_features, train_targets_np_batched, validation_size=0)

---EPOCH 0---
0m 1s (0:0 0.00%) 0.1162
0m 16s (0:10 0.08%) 1.1633
0m 28s (0:20 0.17%) 1.1649
0m 41s (0:30 0.25%) 1.1627
0m 53s (0:40 0.34%) 1.1643
1m 6s (0:50 0.42%) 1.1635
1m 19s (0:60 0.50%) 1.1641
1m 32s (0:70 0.59%) 1.1647
1m 44s (0:80 0.67%) 1.1636
1m 57s (0:90 0.76%) 1.1651
2m 10s (0:100 0.84%) 1.1641
2m 23s (0:110 0.92%) 1.1620
2m 36s (0:120 1.01%) 1.1612
2m 49s (0:130 1.09%) 1.1625
3m 1s (0:140 1.18%) 1.1632
3m 14s (0:150 1.26%) 1.1614
3m 27s (0:160 1.34%) 1.1618
3m 40s (0:170 1.43%) 1.1651
3m 53s (0:180 1.51%) 1.1616
4m 6s (0:190 1.60%) 1.1639
4m 19s (0:200 1.68%) 1.1626
4m 32s (0:210 1.76%) 1.1604
4m 45s (0:220 1.85%) 1.1616
4m 58s (0:230 1.93%) 1.1618
5m 11s (0:240 2.02%) 1.1610
5m 24s (0:250 2.10%) 1.1605
5m 37s (0:260 2.19%) 1.1624
5m 50s (0:270 2.27%) 1.1607
6m 3s (0:280 2.35%) 1.1609
6m 16s (0:290 2.44%) 1.1621
6m 29s (0:300 2.52%) 1.1619
6m 42s (0:310 2.61%) 1.1619
6m 55s (0:320 2.69%) 1.1607
7m 8s (0:330 2.77%) 1.1598
7m 21s (0:340 2.86%) 1.1624
7m 34s (0:350 2.94%) 1.

60m 26s (0:2750 23.11%) 1.1401
60m 39s (0:2760 23.20%) 1.1433
60m 52s (0:2770 23.28%) 1.1391
61m 6s (0:2780 23.36%) 1.1415
61m 19s (0:2790 23.45%) 1.1430
61m 32s (0:2800 23.53%) 1.1393
61m 45s (0:2810 23.62%) 1.1430
61m 59s (0:2820 23.70%) 1.1434
62m 12s (0:2830 23.78%) 1.1420
62m 25s (0:2840 23.87%) 1.1415
62m 38s (0:2850 23.95%) 1.1402
62m 52s (0:2860 24.04%) 1.1406
63m 5s (0:2870 24.12%) 1.1401
63m 18s (0:2880 24.20%) 1.1394
63m 32s (0:2890 24.29%) 1.1403
63m 45s (0:2900 24.37%) 1.1397
63m 58s (0:2910 24.46%) 1.1405
64m 12s (0:2920 24.54%) 1.1398
64m 25s (0:2930 24.62%) 1.1402
64m 38s (0:2940 24.71%) 1.1381
64m 52s (0:2950 24.79%) 1.1405
65m 5s (0:2960 24.88%) 1.1404
65m 18s (0:2970 24.96%) 1.1433
65m 31s (0:2980 25.04%) 1.1395
65m 44s (0:2990 25.13%) 1.1386
65m 58s (0:3000 25.21%) 1.1433
66m 11s (0:3010 25.30%) 1.1416
66m 24s (0:3020 25.38%) 1.1397
66m 37s (0:3030 25.46%) 1.1386
66m 50s (0:3040 25.55%) 1.1378
67m 4s (0:3050 25.63%) 1.1381
67m 17s (0:3060 25.72%) 1.1389
67m 30s (0:3

118m 9s (0:5390 45.30%) 1.1239
118m 23s (0:5400 45.38%) 1.1251
118m 36s (0:5410 45.47%) 1.1242
118m 49s (0:5420 45.55%) 1.1237
119m 3s (0:5430 45.63%) 1.1239
119m 16s (0:5440 45.72%) 1.1248
119m 29s (0:5450 45.80%) 1.1233
119m 42s (0:5460 45.89%) 1.1242
119m 55s (0:5470 45.97%) 1.1252
120m 9s (0:5480 46.05%) 1.1244
120m 22s (0:5490 46.14%) 1.1242
120m 35s (0:5500 46.22%) 1.1228
120m 48s (0:5510 46.31%) 1.1247
121m 2s (0:5520 46.39%) 1.1243
121m 15s (0:5530 46.47%) 1.1258
121m 28s (0:5540 46.56%) 1.1237
121m 41s (0:5550 46.64%) 1.1237
121m 54s (0:5560 46.73%) 1.1225
122m 8s (0:5570 46.81%) 1.1233
122m 21s (0:5580 46.89%) 1.1238
122m 34s (0:5590 46.98%) 1.1239
122m 48s (0:5600 47.06%) 1.1242
123m 1s (0:5610 47.15%) 1.1231
123m 14s (0:5620 47.23%) 1.1210
123m 27s (0:5630 47.31%) 1.1241
123m 40s (0:5640 47.40%) 1.1239
123m 54s (0:5650 47.48%) 1.1243
124m 7s (0:5660 47.57%) 1.1246
124m 21s (0:5670 47.65%) 1.1251
124m 34s (0:5680 47.74%) 1.1229
124m 48s (0:5690 47.82%) 1.1241
125m 1s (0:5700

172m 47s (0:7970 66.98%) 1.1129
173m 0s (0:7980 67.06%) 1.1124
173m 13s (0:7990 67.15%) 1.1096
173m 26s (0:8000 67.23%) 1.1100
173m 39s (0:8010 67.32%) 1.1139
173m 52s (0:8020 67.40%) 1.1109
174m 5s (0:8030 67.48%) 1.1130
174m 18s (0:8040 67.57%) 1.1116
174m 31s (0:8050 67.65%) 1.1066
174m 43s (0:8060 67.74%) 1.1096
174m 56s (0:8070 67.82%) 1.1109
175m 9s (0:8080 67.90%) 1.1086
175m 22s (0:8090 67.99%) 1.1130
175m 35s (0:8100 68.07%) 1.1114
175m 48s (0:8110 68.16%) 1.1119
176m 0s (0:8120 68.24%) 1.1114
176m 13s (0:8130 68.33%) 1.1079
176m 26s (0:8140 68.41%) 1.1129
176m 39s (0:8150 68.49%) 1.1098
176m 52s (0:8160 68.58%) 1.1090
177m 5s (0:8170 68.66%) 1.1104
177m 18s (0:8180 68.75%) 1.1083
177m 31s (0:8190 68.83%) 1.1108
177m 44s (0:8200 68.91%) 1.1092
177m 57s (0:8210 69.00%) 1.1102
178m 10s (0:8220 69.08%) 1.1118
178m 23s (0:8230 69.17%) 1.1101
178m 35s (0:8240 69.25%) 1.1116
178m 48s (0:8250 69.33%) 1.1104
179m 1s (0:8260 69.42%) 1.1100
179m 14s (0:8270 69.50%) 1.1116
179m 27s (0:82

228m 7s (0:10530 88.49%) 1.1030
228m 20s (0:10540 88.58%) 1.1006
228m 34s (0:10550 88.66%) 1.0991
228m 47s (0:10560 88.75%) 1.1008
229m 0s (0:10570 88.83%) 1.0996
229m 13s (0:10580 88.92%) 1.0999
229m 26s (0:10590 89.00%) 1.0999
229m 39s (0:10600 89.08%) 1.0987
229m 52s (0:10610 89.17%) 1.0995
230m 5s (0:10620 89.25%) 1.0999
230m 18s (0:10630 89.34%) 1.0993
230m 31s (0:10640 89.42%) 1.0993
230m 45s (0:10650 89.50%) 1.1013
230m 58s (0:10660 89.59%) 1.1010
231m 11s (0:10670 89.67%) 1.1004
231m 24s (0:10680 89.76%) 1.0975
231m 37s (0:10690 89.84%) 1.1008
231m 50s (0:10700 89.92%) 1.0969
232m 3s (0:10710 90.01%) 1.0997
232m 16s (0:10720 90.09%) 1.0983
232m 29s (0:10730 90.18%) 1.0999
232m 42s (0:10740 90.26%) 1.1005
232m 55s (0:10750 90.34%) 1.0997
233m 9s (0:10760 90.43%) 1.0968
233m 22s (0:10770 90.51%) 1.1009
233m 35s (0:10780 90.60%) 1.0999
233m 48s (0:10790 90.68%) 1.0979
234m 1s (0:10800 90.76%) 1.0985
234m 14s (0:10810 90.85%) 1.1001
234m 27s (0:10820 90.93%) 1.0995
234m 40s (0:1083

283m 48s (1:1230 10.34%) 1.0910
284m 1s (1:1240 10.42%) 1.0890
284m 13s (1:1250 10.51%) 1.0888
284m 26s (1:1260 10.59%) 1.0903
284m 39s (1:1270 10.67%) 1.0865
284m 52s (1:1280 10.76%) 1.0897
285m 4s (1:1290 10.84%) 1.0902
285m 17s (1:1300 10.93%) 1.0929
285m 31s (1:1310 11.01%) 1.0890
285m 44s (1:1320 11.09%) 1.0914
285m 57s (1:1330 11.18%) 1.0885
286m 10s (1:1340 11.26%) 1.0958
286m 23s (1:1350 11.35%) 1.0918
286m 35s (1:1360 11.43%) 1.0915
286m 48s (1:1370 11.51%) 1.0926
287m 1s (1:1380 11.60%) 1.0869
287m 14s (1:1390 11.68%) 1.0891
287m 27s (1:1400 11.77%) 1.0894
287m 39s (1:1410 11.85%) 1.0916
287m 52s (1:1420 11.93%) 1.0887
288m 5s (1:1430 12.02%) 1.0928
288m 18s (1:1440 12.10%) 1.0913
288m 31s (1:1450 12.19%) 1.0901
288m 44s (1:1460 12.27%) 1.0891
288m 56s (1:1470 12.35%) 1.0920
289m 9s (1:1480 12.44%) 1.0901
289m 22s (1:1490 12.52%) 1.0916
289m 35s (1:1500 12.61%) 1.0912
289m 48s (1:1510 12.69%) 1.0864
290m 0s (1:1520 12.77%) 1.0900
290m 13s (1:1530 12.86%) 1.0914
290m 26s (1:15

339m 7s (1:3810 32.02%) 1.0819
339m 20s (1:3820 32.10%) 1.0831
339m 33s (1:3830 32.19%) 1.0857
339m 46s (1:3840 32.27%) 1.0794
339m 59s (1:3850 32.36%) 1.0823
340m 12s (1:3860 32.44%) 1.0842
340m 25s (1:3870 32.52%) 1.0814
340m 38s (1:3880 32.61%) 1.0823
340m 51s (1:3890 32.69%) 1.0802
341m 4s (1:3900 32.78%) 1.0819
341m 17s (1:3910 32.86%) 1.0813
341m 30s (1:3920 32.94%) 1.0803
341m 43s (1:3930 33.03%) 1.0842
341m 56s (1:3940 33.11%) 1.0810
342m 9s (1:3950 33.20%) 1.0847
342m 22s (1:3960 33.28%) 1.0808
342m 35s (1:3970 33.36%) 1.0821
342m 47s (1:3980 33.45%) 1.0823
343m 0s (1:3990 33.53%) 1.0838
343m 13s (1:4000 33.62%) 1.0840
343m 26s (1:4010 33.70%) 1.0828
343m 39s (1:4020 33.78%) 1.0863
343m 52s (1:4030 33.87%) 1.0817
344m 5s (1:4040 33.95%) 1.0834
344m 18s (1:4050 34.04%) 1.0834
344m 31s (1:4060 34.12%) 1.0852
344m 44s (1:4070 34.20%) 1.0841
344m 57s (1:4080 34.29%) 1.0840
345m 10s (1:4090 34.37%) 1.0828
345m 23s (1:4100 34.46%) 1.0818
345m 36s (1:4110 34.54%) 1.0829
345m 49s (1:4

393m 49s (1:6390 53.70%) 1.0745
394m 1s (1:6400 53.79%) 1.0743
394m 14s (1:6410 53.87%) 1.0755
394m 27s (1:6420 53.95%) 1.0733
394m 39s (1:6430 54.04%) 1.0769
394m 52s (1:6440 54.12%) 1.0719
395m 5s (1:6450 54.21%) 1.0753
395m 17s (1:6460 54.29%) 1.0772
395m 30s (1:6470 54.37%) 1.0786
395m 43s (1:6480 54.46%) 1.0754
395m 55s (1:6490 54.54%) 1.0732
396m 8s (1:6500 54.63%) 1.0771
396m 21s (1:6510 54.71%) 1.0741
396m 33s (1:6520 54.79%) 1.0732
396m 46s (1:6530 54.88%) 1.0783
396m 59s (1:6540 54.96%) 1.0745
397m 12s (1:6550 55.05%) 1.0722
397m 24s (1:6560 55.13%) 1.0732
397m 37s (1:6570 55.21%) 1.0770
397m 50s (1:6580 55.30%) 1.0754
398m 2s (1:6590 55.38%) 1.0758
398m 15s (1:6600 55.47%) 1.0756
398m 28s (1:6610 55.55%) 1.0737
398m 41s (1:6620 55.63%) 1.0763
398m 53s (1:6630 55.72%) 1.0787
399m 6s (1:6640 55.80%) 1.0759
399m 19s (1:6650 55.89%) 1.0743
399m 31s (1:6660 55.97%) 1.0712
399m 44s (1:6670 56.06%) 1.0703
399m 57s (1:6680 56.14%) 1.0738
400m 10s (1:6690 56.22%) 1.0773
400m 22s (1:6

448m 44s (1:8970 75.38%) 1.0675
448m 56s (1:8980 75.47%) 1.0681
449m 9s (1:8990 75.55%) 1.0695
449m 22s (1:9000 75.64%) 1.0686
449m 35s (1:9010 75.72%) 1.0707
449m 48s (1:9020 75.80%) 1.0690
450m 0s (1:9030 75.89%) 1.0691
450m 13s (1:9040 75.97%) 1.0687
450m 26s (1:9050 76.06%) 1.0690
450m 38s (1:9060 76.14%) 1.0680
450m 51s (1:9070 76.22%) 1.0690
451m 4s (1:9080 76.31%) 1.0700
451m 17s (1:9090 76.39%) 1.0660
451m 29s (1:9100 76.48%) 1.0686
451m 42s (1:9110 76.56%) 1.0665
451m 54s (1:9120 76.65%) 1.0673
452m 7s (1:9130 76.73%) 1.0723
452m 20s (1:9140 76.81%) 1.0682
452m 33s (1:9150 76.90%) 1.0675
452m 45s (1:9160 76.98%) 1.0695
452m 58s (1:9170 77.07%) 1.0717
453m 11s (1:9180 77.15%) 1.0684
453m 24s (1:9190 77.23%) 1.0694
453m 36s (1:9200 77.32%) 1.0664
453m 49s (1:9210 77.40%) 1.0687
454m 2s (1:9220 77.49%) 1.0667
454m 15s (1:9230 77.57%) 1.0683
454m 27s (1:9240 77.65%) 1.0702
454m 40s (1:9250 77.74%) 1.0686
454m 53s (1:9260 77.82%) 1.0680
455m 6s (1:9270 77.91%) 1.0694
455m 18s (1:92

502m 53s (1:11500 96.65%) 1.0646
503m 5s (1:11510 96.73%) 1.0602
503m 18s (1:11520 96.81%) 1.0657
503m 31s (1:11530 96.90%) 1.0635
503m 44s (1:11540 96.98%) 1.0641
503m 57s (1:11550 97.07%) 1.0640
504m 10s (1:11560 97.15%) 1.0632
504m 23s (1:11570 97.24%) 1.0598
504m 35s (1:11580 97.32%) 1.0617
504m 48s (1:11590 97.40%) 1.0631
505m 1s (1:11600 97.49%) 1.0607
505m 14s (1:11610 97.57%) 1.0612
505m 27s (1:11620 97.66%) 1.0600
505m 40s (1:11630 97.74%) 1.0632
505m 53s (1:11640 97.82%) 1.0610
506m 6s (1:11650 97.91%) 1.0614
506m 19s (1:11660 97.99%) 1.0660
506m 32s (1:11670 98.08%) 1.0591
506m 45s (1:11680 98.16%) 1.0634
506m 58s (1:11690 98.24%) 1.0643
507m 11s (1:11700 98.33%) 1.0631
507m 24s (1:11710 98.41%) 1.0639
507m 37s (1:11720 98.50%) 1.0618
507m 49s (1:11730 98.58%) 1.0652
508m 3s (1:11740 98.66%) 1.0626
508m 16s (1:11750 98.75%) 1.0608
508m 29s (1:11760 98.83%) 1.0647
508m 42s (1:11770 98.92%) 1.0627
508m 55s (1:11780 99.00%) 1.0616
509m 8s (1:11790 99.08%) 1.0606
509m 21s (1:118

560m 11s (2:2230 18.74%) 1.0598
560m 24s (2:2240 18.83%) 1.0578
560m 37s (2:2250 18.91%) 1.0564
560m 50s (2:2260 18.99%) 1.0589
561m 3s (2:2270 19.08%) 1.0575
561m 16s (2:2280 19.16%) 1.0564
561m 29s (2:2290 19.25%) 1.0569
561m 42s (2:2300 19.33%) 1.0598
561m 55s (2:2310 19.41%) 1.0559
562m 9s (2:2320 19.50%) 1.0579
562m 22s (2:2330 19.58%) 1.0582
562m 35s (2:2340 19.67%) 1.0574
562m 48s (2:2350 19.75%) 1.0623
563m 1s (2:2360 19.83%) 1.0563
563m 14s (2:2370 19.92%) 1.0570
563m 27s (2:2380 20.00%) 1.0567
563m 40s (2:2390 20.09%) 1.0549
563m 53s (2:2400 20.17%) 1.0544
564m 6s (2:2410 20.25%) 1.0590
564m 19s (2:2420 20.34%) 1.0578
564m 34s (2:2430 20.42%) 1.0540
564m 50s (2:2440 20.51%) 1.0581
565m 4s (2:2450 20.59%) 1.0575
565m 17s (2:2460 20.67%) 1.0589
565m 30s (2:2470 20.76%) 1.0563
565m 43s (2:2480 20.84%) 1.0591
565m 56s (2:2490 20.93%) 1.0585
566m 9s (2:2500 21.01%) 1.0594
566m 21s (2:2510 21.09%) 1.0573
566m 34s (2:2520 21.18%) 1.0558
566m 47s (2:2530 21.26%) 1.0565
567m 0s (2:254

KeyboardInterrupt: 

In [384]:
train_features[0]

(array([[  0,  11,   1, 367],
        [  0,   7,   6,   1],
        [  0, 132,  20,   1],
        [  0,   6,   1, 367],
        [  0, 168,   1, 367],
        [  0, 126,   1, 367],
        [  0,  28,   1, 367],
        [  0,  11,   1, 367],
        [  0,  32,   1, 367],
        [  0,   9,   1, 367],
        [  0,  20,   1, 367],
        [  0, 133,   6,   1],
        [  0, 310,   6,   1],
        [  0, 291,   1, 367],
        [  0,  71,   1, 367],
        [  0, 313,   1, 367],
        [  0,  55,   1, 367],
        [  0,  64,   6,   1],
        [  0,   4,   6,   1],
        [  0,  79,   1, 367],
        [  0,   5,   1, 367],
        [  0,  17,   1, 367],
        [  0,  64,  20,   1],
        [  0,  68,   6,   1],
        [  0,  32,   1, 367],
        [  0,   6,   1, 367],
        [  0,   4, 167,   1],
        [  0,  32,   1, 367],
        [  0,  22,   1, 367],
        [  0,   6,   1, 367],
        [  0,   6,   1, 367],
        [  0,  15,  20,   1],
        [  0, 133,   6,   1],
        [ 

In [383]:
train_targets_np_batched[0]

array([[ 11,   1, 367, 367],
       [  7,   6,   1, 367],
       [132,  20,   1, 367],
       [  6,   1, 367, 367],
       [168,   1, 367, 367],
       [126,   1, 367, 367],
       [ 28,   1, 367, 367],
       [ 11,   1, 367, 367],
       [ 32,   1, 367, 367],
       [  9,   1, 367, 367],
       [ 20,   1, 367, 367],
       [133,   6,   1, 367],
       [310,   6,   1, 367],
       [291,   1, 367, 367],
       [ 71,   1, 367, 367],
       [313,   1, 367, 367],
       [ 55,   1, 367, 367],
       [ 64,   6,   1, 367],
       [  4,   6,   1, 367],
       [ 79,   1, 367, 367],
       [  5,   1, 367, 367],
       [ 17,   1, 367, 367],
       [ 64,  20,   1, 367],
       [ 68,   6,   1, 367],
       [ 32,   1, 367, 367],
       [  6,   1, 367, 367],
       [  4, 167,   1, 367],
       [ 32,   1, 367, 367],
       [ 22,   1, 367, 367],
       [  6,   1, 367, 367],
       [  6,   1, 367, 367],
       [ 15,  20,   1, 367],
       [133,   6,   1, 367],
       [158,  20,   1, 367],
       [ 20,  

In [394]:
len(train_features)//2

5949

In [392]:
train_features[:len(train_features)//2]

TypeError: slice indices must be integers or None or have an __index__ method

In [395]:
with open("train_features_1.pkl", "wb") as file:
    pickle.dump(train_features[:len(train_features)//2], file)
    
    
with open("train_features_2.pkl", "wb") as file:
    pickle.dump(train_features[len(train_features)//2:], file)    

In [382]:
with open("train_targets.pkl", "wb") as file:
    pickle.dump(train_targets_np_batched, file)

In [388]:
with open("idx2word.pkl", "wb") as file:
    pickle.dump(idx2word, file)

# Julia start running code here

In [377]:
import dnc
import torch
import torch.nn as nn
import time
import math
import numpy as np
import pickle

In [ ]:
class DNCEncoder(nn.Module):
    def __init__(self, vocab_size, embed_dim, color_dim):
        super(DNCEncoder, self).__init__()
        self.embed = nn.Embedding(vocab_size, embed_dim)
        self.rnn = dnc.DNC(
          input_size=embed_dim + color_dim,
          hidden_size=128,
          rnn_type='lstm',
          num_layers=4,
          nr_cells=100,
          cell_size=32,
          read_heads=4,
          batch_first=True,
          gpu_id=-1,
          debug=True
        )
        self.decoder = nn.Linear(embed_dim + color_dim, vocab_size) # don't predict over padding tag
        self.logsoftmax = nn.LogSoftmax(dim=1)
        
        self.vocab_size = vocab_size
        
    def forward(self, caption, color):
        embeds = self.embed(caption)
        #embeds = nn.utils.pack_padded_sequence(embeds, caption_lens, batch_first=True)
        #print(embeds.type())
        #print(color.type())
        color_reps = color.repeat(1, caption.shape[1], 1) # repeat color for number of tokens in captions
        #print(color_reps)
        # concatenate colors to caption
        inputs = torch.cat((embeds, color_reps), dim=2) # cat along the innermost dimension
        #print(inputs.size())
        # dnc magic
        (controller_hidden, memory, read_vectors) = (None, None, None)
        output, (controller_hidden, memory, read_vectors), debug_memory = \
          rnn(inputs, (controller_hidden, memory, read_vectors), reset_experience=True)


        result = self.decoder(output)
        return self.logsoftmax(result)

In [369]:


class PytorchModel():

    def __init__(self,  model, optimizer=torch.optim.Adadelta,
                 criterion=nn.NLLLoss, lr=0.2, num_epochs=30, batch_size=1):
        """
        Right now this is kind of ugly because you have to pass literally all of the experiment arguments
        to this constructor. 
        """
        self.model = model

        self.optimizer = optimizer
        self.criterion = criterion

        # misc args:
        self.lr = lr
        self.num_epochs = num_epochs
        self.batch_size = batch_size

        # for reproducibility, store training pairs
        self.features  = None
        self.target = None

        # also make sure the model has been initialized before we do anything
        self.initialized = False

    def fit(self, X, y, validation_size = 3000):
        """
        The main sklearn-like function that takes input features X (in
        a list or array - we use color features and caption features
        for pytorch models) and targets, y, also a np array. The function
        just stores them and calls its internal train model function
        """

        # set up validation data if necessary
        if validation_size > 0:
            self.features = X[:-validation_size]
            self.targets = y[:-validation_size]
            self.val_features= X[-validation_size:]
            self.val_targets = y[-validation_size:]
        else:
            self.features = X
            self.targets = y 
            self.val_features = None
            self.val_features = None

        self.train_model()

    # from https://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html
    def asMinutes(self, s):
        m = math.floor(s / 60)
        s -= m * 60
        return '%dm %ds' % (m, s)


    def init_model(self, **model_params):
        """
        Interesting quirk - in most cases, the model takes the vocabulary size
        as an input, but there's no way for the user to know what the vocab
        size is before calling the init_model method. Even though it's kinda ugly,
        what we can do instead is pass all of the model params (named) minus
        the vocab size to this function, and it will create the model. I don't 
        really like this but it works for now
        """
        if self.initialized:
            return

        self.model = self.model(**model_params)
        self.initialized = True

    def train_iter(self, caption, colors, target, criterion):
        """
        Generate predictions based on the caption and color. Caculate loss against
        the target using the criterion and optimize using the optimizer. All subclasses
        will do this a little bit differently, so do implement this in the subclasses
        """
        pass


    def train_model(self):
        if not self.initialized:
            print("Make sure you initialize the model with the parameters you want")
            return


        optimizer = self.optimizer(lr=self.lr, params=self.model.parameters())
        criterion = self.criterion()

        start_time = time.time()
        store_losses_every = 100
        print_losses_every = 10
        self.stored_losses = [] # theoretically we store losses so we can plot them later - 
                                # I don't think this part of the code works though. What we
                                # can do instead is take a few thousand or so training examples
                                # out and use them for "evaluation" every 1 epoch or so
        for epoch in range(self.num_epochs):
            print("---EPOCH {}---".format(epoch))
            stored_loss_total = 0
            print_loss_total = 0

            for i, pair in enumerate(self.features):
                caption, colors = pair
                if self.batch_size == 1:
                    caption = torch.tensor([caption], dtype=torch.long)
                    colors = torch.tensor([colors], dtype=torch.float)
                    target = torch.tensor([self.targets[i]]) 
                else:
                    caption = torch.tensor(caption, dtype=torch.long)
                    colors = torch.tensor(colors, dtype=torch.float)
                    target = torch.tensor(self.targets[i]) 


                optimizer.zero_grad()
                loss = self.train_iter(caption, colors, target, criterion)
                loss.backward()
                optimizer.step()
                stored_loss_total += loss.item()
                print_loss_total += loss.item()

                if i % print_losses_every == 0:
                    print_loss_avg = print_loss_total / print_losses_every
                    print("{} ({}:{} {:.2f}%) {:.4f}".format(self.asMinutes(time.time() - start_time),
                                                      epoch, i, i/len(self.features)*100,
                                                      print_loss_avg))
                    print_loss_total = 0

                if i % store_losses_every == 0:
                    stored_loss_avg = stored_loss_total / store_losses_every
                    self.stored_losses.append(stored_loss_avg)
                    stored_loss_total = 0

            # run validation data after every epoch
            self.save_model("checkpoint_{}.params".format(epoch))
            self.validate_model(epoch, criterion)

    def validate_model(self, epoch_num, criterion):
        if self.val_features is None:
            return

        # run validation
        total_loss = 0
        self.model.eval()
        with torch.no_grad():
            for i, pair in enumerate(self.val_features):
                caption, colors = pair
                if self.batch_size == 1:
                    caption = torch.tensor([caption], dtype=torch.long)
                    colors = torch.tensor([colors], dtype=torch.float)
                    target = torch.tensor([self.targets[i]]) 
                else:
                    caption = torch.tensor(caption, dtype=torch.long)
                    colors = torch.tensor(colors, dtype=torch.float)
                    target = torch.tensor(self.targets[i]) 
                 
                total_loss += self.train_iter(caption, colors, target, criterion).item()
            print("="*25)
            print("AFTER EPOCH {} - AVERAGE VALIDATION LOSS: {}".format(i, total_loss / len(self.val_features)))
            print("="*25)
        self.model.train()


    def load_model(self, filename):
        """
        Load model from saved file at filename
        """
        if not self.initialized:
            self.init_model
        self.model.load_state_dict(torch.load(filename))

    def save_model(self, filename):
        """
        Save model to file at filename
        """
        torch.save(self.model.state_dict(), filename)

In [ ]:
# shamelessly copied from beam search code
from queue import PriorityQueue

class BeamNode():
    def __init__(self, log_prob, tokens, ended):
        self.log_prob = log_prob
        self.tokens = tokens
        self.ended = ended

    def score(self):
        return -self.log_prob

    def __eq__(self, other):
        return self.score() == other.score()

    def __lt__(self, other):
        return self.score() < other.score()
    

class DNCSpeaker(PytorchModel):
    
    def predict(self, X, sample=1, beam_width=5):
        all_tokens = []
        self.model.eval()
        max_gen_len = 20
    
        self.model.eval()
        with torch.no_grad():
            for i, feature in enumerate(X):
                caption, colors = feature
                if self.batch_size == 1:
                    caption = torch.tensor([caption], dtype=torch.long)
                    colors = torch.tensor([colors], dtype=torch.float)
                else:
                    caption = torch.tensor([caption], dtype=torch.long)
                    colors = torch.tensor([colors], dtype=torch.float)

    
                beam_nodes = PriorityQueue()
                ended_list = []
    
                tokens = caption[:, 0].view(-1, 1) # begin at start token
                start = BeamNode(0, tokens, False)
                beam_nodes.put(start)
    
                for i in range(max_gen_len + 1):
                    node = beam_nodes.get()
                    if node.ended:
                        ended_list.append(np.array(node.tokens[0].numpy()))
                        if len(ended_list) == sample:
                            break
                    else:
                        tokens = node.tokens
                        vocab_preds = self.model(colors, tokens)[:,-1:,:] # just distribution over last token
                        log_probs, prediction_indices = vocab_preds.topk(beam_width, dim=2)  # taking the topk predictions
                        for j in range(beam_width):
                            prediction_index = prediction_indices[:,-1,j:j+1] # a single prediction
                            log_prob = log_probs[0][0][j].item()
                            updated_tokens = tokens.clone()
                            updated_tokens = torch.cat((updated_tokens, prediction_index), dim=1)
                            updated_log_prob = node.log_prob + log_prob
                            ended = ((i == max_gen_len - 1) or (prediction_index.item() == caption[:, -1].view(-1, 1)))
                            new_node = BeamNode(updated_log_prob, updated_tokens, ended)
                            beam_nodes.put(new_node)
                if sample == 1: # for backwards compatability
                    all_tokens.append(np.array(ended_list))
                else:
                    all_tokens.append(ended_list)
        return all_tokens
    
    def train_iter(self, caption_tensor, color_tensor, target_tensor, criterion):
        model_output = self.model(caption_tensor, color_tensor)
        
        #model_output = model_output[:, :-1, :].squeeze(0)
        model_output = model_output.view(-1, self.model.vocab_size)
        target_tensor = target_tensor.view(-1)
        #print("output shape:", model_output.size())
        #print("target shape:", target_tensor.size())
        loss = criterion(model_output, target_tensor)
        return loss

In [398]:
# load data
train_features_1 = None
with open("train_features_1.pkl", "rb") as file:
    train_features_1 = pickle.load(file)
    
train_features_2 = None
with open("train_features_2.pkl", "rb") as file:
    train_features_2 = pickle.load(file)
    
train_features = train_features_1 + train_features_2

train_targets = None
with open("train_targets.pkl", "rb") as file:
    train_targets = pickle.load(file)
    
idx2word = None
with open("idx2word.pkl", "rb") as file:
    idx2word = pickle.load(file)

In [ ]:
# load model
dnc_speaker = DNCSpeaker(DNCEncoder, num_epochs=5, batch_size=128)
dnc_speaker.init_model(vocab_size = len(idx2word), embed_dim=100, color_dim=3)
dnc_speaker.load_model("checkpoint_0.params")

In [ ]:
# train model
dnc_speaker.fit(train_features, train_targets, validation_size=0) # things break if validation size is nonzero for some reason